version: '3'
services:
  backend:
    build: ./backend/
    tty: true
    volumes:
      - './backend/:/usr/src/app/'
    ports:
      - '8080:8080'
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo
  redis:
    image: redis
    tty: true
