version: '3'
services:
  backendnginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - /var/log/nginx:/var/log/nginx
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
  backend:
    build: ./backend/
    tty: true
    volumes:
      - './backend/:/usr/src/app/'
    ports:
      - '8080:8080'
    environment:
      - 'DEBUG=express:*'
      - NODE_ENV=development
    depends_on:
      - mongo
      - redis
  socketioproxy:
    image: nginx
    ports:
      - 8000:80
    volumes:
      - ./nginx/socket.io/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - websocket
  websocket:
    build: ./websocket/
    tty: true
    volumes:
      - './websocket/:/usr/src/app/'
    depends_on:
      - redis
  client:
    build: ./client/
    tty: true
    volumes:
      - './client/:/usr/src/app/'
    ports:
      - '3000:3000'
    depends_on:
      - websocket
  game:
    build: ./game/
    tty: true
    volumes:
      - './game/:/usr/src/app/'
  mongo:
    image: mongo
    tty: true
  redis:
    image: redis
    tty: true
