version: '3'
services:
  backend:
    build: ./backend/
    tty: true
    volumes:
      - './backend/:/usr/src/app/'
    ports:
      - '8080:8080'
    depends_on:
      - mongo
      - redis
  websocket:
    build: ./websocket/
    tty: true
    volumes:
      - './websocket/:/usr/src/app/'
    ports:
      - '8000:8000'
    depends_on:
      - redis
  client:
    build: ./client/
    tty: true
    volumes:
      - './client/:/usr/src/app/'
    ports:
      - '3000:8080'
    depends_on:
      - websocket
  mongo:
    image: mongo
    tty: true
  redis:
    image: redis
    tty: true
